### ISSUE TITLE
IPv6 should probably not match bare IPv6

### ISSUE THREAD

**Issue by silverwind** [silverwind/cidr-regex#5]
I expected a bare IPv6 to not match as it's missing a prefix, similar to how it works on IPv4:

````js
> require(".").cidrv6.test("::1")
true
> require(".").cidrv4.test("1.2.3.4")
false
````

This way, one could use both this module and `ip-regex` together to discern IPs from CIDRs.

**Comment by flipjs** [comment]
Hi @silverwind . A PR is very much appreciated. Are you up to it? Thanks.

**Comment by silverwind** [comment]
Hmm yes, but it would be pretty much a rewrite of the module. Are you okay with me dropping the build step? I'd target node >= 4.

**Comment by flipjs** [comment]
@silverwind Actually, if you dont mind, I can transfer the ownership to you (or anyone else). I can no longer maintain this as I never use this anymore.

**Comment by silverwind** [comment]
Sure, I'd be interested in taking over both `cidr-regex` and `is-cidr` and taking care of them.
