### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by flipjs** [silverwind/cidr-regex#6]
Hi @silverwind. I initiated the transfer already to your account.

Regarding npm, I am not sure how to do it. Tried `npm adduser` but cancelled it midway because I got confused with the questions/prompt. If you know how to, can you guide me please so I can transfer the npm ownership as well. Thanks.

**Comment by silverwind** [comment]
Hmm, I don't see any indication of the move. IIRC, the recpient shouldn't have to confirm anything, the repo will just move after you typed its name. If it doesn't work out, I can always just fork and push to new repositories, no issue.

As for NPM, I suggest simply adding me as a collaborator on the web interface, and if all goes well, you can probably "leave" afterwards (if you like, but I wouldn't mind if you stayed).

**Comment by flipjs** [comment]
That is strange. In the repo settings, I'm seeing status "This repository is being transferred to @silverwind".

I added you as collaborator just now. Maybe that will do the trick?

**Comment by flipjs** [comment]
Just added you as collaborator on npm.

**Comment by silverwind** [comment]
Thanks. Do you want to transfer the Github repos to me, so the issues/prs are not lost? You can do that in the repo settings with the Transfer button. Otherwise, I'll recreate new ones.

**Comment by flipjs** [comment]
Have you received the notification about the transfer? It still says in progress.

I'd like to keep the issues/pr intact, but that shouldnt delete those when transferring ownership? Also, I dont see an option for that in the settings.

**Comment by silverwind** [comment]
Ah, found two mails in my inbox for it that I missed earlier, but the links in them have expired. Can you restart?

**Comment by flipjs** [comment]
Here it is:

https://help.github.com/articles/about-repository-transfers/

It says All of the issues and pull requests remain intact when transferring a repository".

**Comment by flipjs** [comment]
I aborted the transfer and did a retry. Please check your email inbox.

**Comment by silverwind** [comment]
That worked, thanks. And sorry for missing that earlier mail!

https://github.com/silverwind/cidr-regex
https://github.com/silverwind/is-cidr
